name: My Workflow

on: 
  workflow_dispatch:
    inputs:
      servername:
        description: 'enter server name'
        required: true
        default: 'DWCL1D'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Example step
      
        run: |
          ./fileprint.ps1
