name: Sanity Check report

on: 
   workflow_dispatch:
    inputs:
     servernames:
      description: 'select servernames'
      required: true
      default: ''
      options: ['DWSQL1/ODS','DWSQL1/OLTP','QWSQL1/ODS','QWSQL1/OLTP','PTCL1A/ODS','PTCL1B/OLTP','PCL4A/ODS','PCL4B/OLTP']

     username:
        description: 'enter username'
        required: true
     password:
          description: 'enter a password'
          required: true
     From:
            description: ''
            required: true
            default: ''
            options: ['Aparna.Sagi@teachforamerica.org','satish.jagarlamudi@teachforamerica.org','dbaprod@teachforamerica.org']
     To:
              description: ''
              required: true
              default: ''
              options: ['Aparna.Sagi@teachforamerica.org','satish.jagarlamudi@teachforamerica.org','dbaprod@teachforamerica.org']
jobs:
  sanity_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Select server
        
        run: |
         ./check_report.ps1
